version: '3'
services:
  rails_app:
    build: docker/app/
    entrypoint: tail -f /dev/null
    volumes:
    - ./:/var/www/app:cached
    networks:
      - rails_app_network
  db:
    image: postgres
    restart: always
    ports:
    - 65432:5432
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - rails_app_network
networks:
  rails_app_network: